version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    update-types: major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
